// examples/vuejs/src/components/clocks/Clock1.vue
<template>
  <div class="clockFace">
    <div class="time">{{time}}</div>
    <div class="date">{{date}}</div>
  </div>
</template>
<script>
import clockMixin from './clock.mixin'
import { months, pad0 } from '../../constants'

export default {
  name: 'Clock1',
  mixins: [clockMixin],
  data () {
    return {
      time: '',
      date: ''
    }
  },
  watch: {
    dateTime (newValue) {
      if (newValue) {
        this.date = `${newValue.getDate()} ${months[newValue.getMonth()]}, ${newValue.getFullYear()}`
        this.time = `${pad0(newValue.getHours())}:${pad0(newValue.getMinutes())}:${pad0(newValue.getSeconds())}`
      }
    }
  }
}
</script>
<style lang="scss" scoped>
.clockFace {
  width: 200px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  font-size: 1.5rem;
  font-family: sans-serif;

  .time {
    color: blue;
  }

  .date {
    color: green;
  }
}
</style>

// examples/reactjs/src/clocks/Clock1.js
import { useEffect, useState } from 'react'
import { months, pad0, useDateTime } from '../constants'
import styles from './clock1.module.css'

export function Clock1 ({ observable, fromApi }) {
  const [time, setTime] = useState('')
  const [date, setDate] = useState('')
  const dateTime = useDateTime(observable, fromApi)

  useEffect(() => {
    if (dateTime) {
        setDate(`${dateTime.getDate()} ${months[dateTime.getMonth()]}, ${dateTime.getFullYear()}`)
        setTime(`${pad0(dateTime.getHours())}:${pad0(dateTime.getMinutes())}:${pad0(dateTime.getSeconds())}`)
    }
  }, [dateTime])

  return (
    <div className={styles.clockFace}>
      <span className={styles.time}>{time}</span>
      <span className={styles.date}>{date}</span>
    </div>
  )
}
